/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.clipimagedemo;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int mm_Font=0x7f050002;
        /** 背景颜色
         */
        public static final int mm_background=0x7f050001;
        public static final int mm_hint_Font=0x7f050003;
        public static final int mm_line_color=0x7f050004;
        public static final int mm_primary_code=0x7f050005;
        public static final int mm_transparent=0x7f050000;
    }
    public static final class dimen {
        public static final int activity_horizontal_margin=0x7f060008;
        public static final int activity_vertical_margin=0x7f060009;
        public static final int mm_dialog_height_1=0x7f060002;
        public static final int mm_dialog_height_2=0x7f060004;
        public static final int mm_dialog_height_3=0x7f060006;
        public static final int mm_dialog_width_1=0x7f060003;
        public static final int mm_dialog_width_2=0x7f060005;
        public static final int mm_dialog_width_3=0x7f060007;
        /** 高度控制
         */
        public static final int mm_import_box_height=0x7f060000;
        public static final int mm_import_box_width=0x7f060001;
    }
    public static final class drawable {
        public static final int app_banner=0x7f020000;
        public static final int app_icon=0x7f020001;
        public static final int iv_union_login=0x7f020002;
        public static final int iv_union_logo=0x7f020003;
        public static final int iv_union_pay=0x7f020004;
        public static final int iv_union_switch=0x7f020005;
        public static final int mm_background=0x7f020006;
        public static final int mm_background2=0x7f020007;
        public static final int mm_bt_common_hnit_no=0x7f020008;
        public static final int mm_bt_common_hnit_par=0x7f020009;
        public static final int mm_bt_common_hnit_sele=0x7f02000a;
        public static final int mm_button1_ena=0x7f02000b;
        public static final int mm_button1_no=0x7f02000c;
        public static final int mm_button1_par=0x7f02000d;
        public static final int mm_button1_sele=0x7f02000e;
        public static final int mm_button2_ena=0x7f02000f;
        public static final int mm_button2_no=0x7f020010;
        public static final int mm_button2_par=0x7f020011;
        public static final int mm_button2_sele=0x7f020012;
        public static final int mm_button3_ena=0x7f020013;
        public static final int mm_button3_no=0x7f020014;
        public static final int mm_button3_par=0x7f020015;
        public static final int mm_button3_sele=0x7f020016;
        public static final int mm_checkbox_1=0x7f020017;
        public static final int mm_checkbox_2=0x7f020018;
        public static final int mm_code=0x7f020019;
        public static final int mm_coupon_icon=0x7f02001a;
        public static final int mm_coupon_icon_2=0x7f02001b;
        public static final int mm_float_loge=0x7f02001c;
        public static final int mm_float_red=0x7f02001d;
        public static final int mm_input_box_bg=0x7f02001e;
        public static final int mm_logo=0x7f02001f;
        public static final int mm_order_icon=0x7f020020;
        public static final int mm_pass=0x7f020021;
        public static final int mm_pay_coupon_icon=0x7f020022;
        public static final int mm_pay_rec=0x7f020023;
        public static final int mm_phone=0x7f020024;
        public static final int mm_phone2=0x7f020025;
        public static final int mm_phone_bind_icon=0x7f020026;
        public static final int mm_phone_login=0x7f020027;
        public static final int mm_qq=0x7f020028;
        public static final int mm_quick_login=0x7f020029;
        public static final int mm_read_info=0x7f02002a;
        public static final int mm_register=0x7f02002b;
        public static final int mm_sele=0x7f02002c;
        public static final int mm_tick=0x7f02002d;
        public static final int mm_title_bar_close=0x7f02002e;
        public static final int mm_title_bar_return=0x7f02002f;
        public static final int mm_trumpet=0x7f020030;
        public static final int mm_trumpet_2=0x7f020031;
        public static final int mm_unread_info=0x7f020032;
        public static final int mm_unsele=0x7f020033;
        public static final int mm_user_icon=0x7f020034;
        public static final int mm_user_name=0x7f020035;
        public static final int mm_vip=0x7f020036;
        public static final int mm_wait=0x7f020037;
        public static final int mm_waitint_shap=0x7f020038;
        public static final int mm_weiuu_bg2=0x7f020039;
        public static final int union_aaa_splash=0x7f02003a;
        public static final int union_title_bg=0x7f02003b;
        public static final int xlistview_arrow=0x7f02003c;
    }
    public static final class id {
        public static final int albumBtn=0x7f090095;
        public static final int bt_1=0x7f090014;
        public static final int bt_2=0x7f090013;
        public static final int bt_3=0x7f090012;
        public static final int bt_change_user=0x7f09003f;
        public static final int bt_confirm=0x7f090009;
        public static final int bt_login=0x7f090034;
        public static final int bt_next=0x7f09006a;
        public static final int bt_register=0x7f090069;
        public static final int bt_return_login=0x7f09006d;
        public static final int bt_right_button=0x7f09002f;
        public static final int cancleBtn=0x7f090003;
        public static final int cancleMenuBtn=0x7f090096;
        public static final int captureBtn=0x7f090094;
        public static final int clipImageLayout=0x7f090000;
        public static final int dpb_download=0x7f090022;
        public static final int dpb_game_download=0x7f09001d;
        public static final int et_import=0x7f09002d;
        public static final int ff_content=0x7f090068;
        public static final int fl_left_content=0x7f090075;
        public static final int fl_list_supre=0x7f090058;
        public static final int fl_right_content=0x7f090076;
        public static final int fl_wh=0x7f090078;
        public static final int gv_list=0x7f090077;
        public static final int hlv_game_list=0x7f090020;
        public static final int hlv_list=0x7f090059;
        public static final int ib_cardID=0x7f090008;
        public static final int ib_code=0x7f09000f;
        public static final int ib_name=0x7f090007;
        public static final int ib_new_2_password=0x7f090011;
        public static final int ib_new_password=0x7f090010;
        public static final int ib_pass=0x7f090033;
        public static final int ib_phone=0x7f09000e;
        public static final int ib_userName=0x7f090032;
        public static final int ibv_code=0x7f09006b;
        public static final int ibv_new_pass=0x7f09006c;
        public static final int ibv_phone=0x7f09006f;
        public static final int ibv_qq=0x7f09006e;
        public static final int im_checkbox=0x7f090064;
        public static final int im_coupon_hint=0x7f090048;
        public static final int im_coupon_icon=0x7f090055;
        public static final int im_direction=0x7f09002a;
        public static final int im_game_icon=0x7f09001a;
        public static final int im_icon=0x7f090026;
        public static final int im_icon_1=0x7f09005f;
        public static final int im_icon_2=0x7f090062;
        public static final int im_item_icon=0x7f090079;
        public static final int im_left=0x7f090071;
        public static final int im_loading=0x7f09003e;
        public static final int im_pay_icon=0x7f090066;
        public static final int im_phone_login=0x7f090039;
        public static final int im_quick_login=0x7f090036;
        public static final int im_register=0x7f09003c;
        public static final int im_return=0x7f090070;
        public static final int im_right=0x7f090072;
        public static final int im_sele=0x7f090067;
        public static final int im_tick=0x7f09000b;
        public static final int im_trumpet=0x7f09004c;
        public static final int im_user_icon=0x7f090080;
        public static final int im_vip=0x7f09007d;
        public static final int im_wait=0x7f090083;
        public static final int imageView=0x7f090093;
        public static final int imageView1=0x7f090099;
        public static final int iv_icon=0x7f090016;
        public static final int iv_left_icon=0x7f09002c;
        public static final int iv_pay_icon=0x7f090050;
        public static final int iv_pay_recommend=0x7f090052;
        public static final int layout=0x7f090001;
        public static final int ll_Super=0x7f090030;
        public static final int ll_coupon=0x7f090047;
        public static final int ll_line=0x7f09005d;
        public static final int ll_parent=0x7f09002b;
        public static final int ll_pay_1=0x7f09005e;
        public static final int ll_pay_2=0x7f090061;
        public static final int ll_phone_login=0x7f090038;
        public static final int ll_quick_login=0x7f090035;
        public static final int ll_register=0x7f09003b;
        public static final int ll_super=0x7f090004;
        public static final int ll_super2=0x7f090074;
        public static final int ll_super3=0x7f09007c;
        public static final int ll_super_1=0x7f090045;
        public static final int ll_super_2=0x7f090019;
        public static final int ll_super_3=0x7f09004b;
        public static final int ll_super_4=0x7f09004e;
        public static final int ll_super_5=0x7f09004f;
        public static final int ll_temp=0x7f090027;
        public static final int ll_user_super=0x7f090006;
        public static final int loading_container=0x7f090082;
        public static final int loading_tv=0x7f090085;
        public static final int ltbv_title=0x7f090031;
        public static final int lv_list=0x7f090024;
        public static final int mm_inform_item_sup=0x7f090025;
        public static final int okBtn=0x7f090002;
        public static final int pj_float_view_icon_imageView=0x7f090087;
        public static final int progress_horizontal=0x7f090098;
        public static final int tbv_title=0x7f090005;
        public static final int text=0x7f090097;
        public static final int tv_autonym_hini=0x7f09000c;
        public static final int tv_autonym_info=0x7f09000d;
        public static final int tv_copy=0x7f090044;
        public static final int tv_coupon=0x7f090057;
        public static final int tv_coupon_hint=0x7f090056;
        public static final int tv_coupon_money=0x7f090049;
        public static final int tv_game_content=0x7f09001c;
        public static final int tv_game_icon=0x7f090021;
        public static final int tv_game_tag=0x7f090023;
        public static final int tv_game_title=0x7f09001b;
        public static final int tv_hint=0x7f09000a;
        public static final int tv_hint_2=0x7f090065;
        public static final int tv_hint_name=0x7f090081;
        public static final int tv_item_title=0x7f09007a;
        public static final int tv_line=0x7f090073;
        public static final int tv_line1=0x7f09001e;
        public static final int tv_line2=0x7f09001f;
        public static final int tv_line3=0x7f090046;
        public static final int tv_line4=0x7f09004a;
        public static final int tv_line5=0x7f090054;
        public static final int tv_money=0x7f090043;
        public static final int tv_more_pay=0x7f090053;
        public static final int tv_name=0x7f090017;
        public static final int tv_order_number=0x7f090042;
        public static final int tv_pay_text=0x7f090051;
        public static final int tv_phone_login=0x7f09003a;
        public static final int tv_points=0x7f09007b;
        public static final int tv_productName=0x7f09005b;
        public static final int tv_product_price=0x7f09005c;
        public static final int tv_quick_login=0x7f090037;
        public static final int tv_red=0x7f090018;
        public static final int tv_red_dot=0x7f090088;
        public static final int tv_register=0x7f09003d;
        public static final int tv_right_text=0x7f09002e;
        public static final int tv_temp=0x7f090015;
        public static final int tv_text=0x7f09005a;
        public static final int tv_text_1=0x7f090060;
        public static final int tv_text_2=0x7f090063;
        public static final int tv_time=0x7f090029;
        public static final int tv_tips=0x7f090040;
        public static final int tv_title=0x7f090028;
        public static final int tv_trumpet_hint=0x7f09004d;
        public static final int tv_vip=0x7f09007e;
        public static final int tv_vip_hint=0x7f09007f;
        public static final int web_content=0x7f090086;
        public static final int web_view=0x7f090084;
        public static final int xlistview_footer_content=0x7f090089;
        public static final int xlistview_footer_hint_textview=0x7f09008b;
        public static final int xlistview_footer_progressbar=0x7f09008a;
        public static final int xlistview_header_arrow=0x7f090091;
        public static final int xlistview_header_content=0x7f09008c;
        public static final int xlistview_header_hint_textview=0x7f09008e;
        public static final int xlistview_header_progressbar=0x7f090092;
        public static final int xlistview_header_text=0x7f09008d;
        public static final int xlistview_header_time=0x7f090090;
        public static final int xlistview_header_time_hint=0x7f09008f;
        public static final int xls_content=0x7f090041;
    }
    public static final class layout {
        public static final int crop_image_layout=0x7f030000;
        public static final int mm_autonym=0x7f030001;
        public static final int mm_autonym_succ=0x7f030002;
        public static final int mm_binding_phone=0x7f030003;
        public static final int mm_change_pass=0x7f030004;
        public static final int mm_common_dialog=0x7f030005;
        public static final int mm_float_item=0x7f030006;
        public static final int mm_game_rec=0x7f030007;
        public static final int mm_game_rec_item=0x7f030008;
        public static final int mm_game_rec_item_old=0x7f030009;
        public static final int mm_game_rec_old=0x7f03000a;
        public static final int mm_inform=0x7f03000b;
        public static final int mm_inform_item=0x7f03000c;
        public static final int mm_inform_item_notinfo=0x7f03000d;
        public static final int mm_input_box_view=0x7f03000e;
        public static final int mm_login=0x7f03000f;
        public static final int mm_login_in=0x7f030010;
        public static final int mm_login_phone=0x7f030011;
        public static final int mm_non_payment=0x7f030012;
        public static final int mm_non_payment_item=0x7f030013;
        public static final int mm_pay=0x7f030014;
        public static final int mm_pay_2=0x7f030015;
        public static final int mm_pay_2_item=0x7f030016;
        public static final int mm_pay_3=0x7f030017;
        public static final int mm_pay_fast=0x7f030018;
        public static final int mm_pay_pop_item=0x7f030019;
        public static final int mm_prompt_box=0x7f03001a;
        public static final int mm_register=0x7f03001b;
        public static final int mm_retrieve_pass=0x7f03001c;
        public static final int mm_retrieve_pass_phone=0x7f03001d;
        public static final int mm_retrieve_pass_service=0x7f03001e;
        public static final int mm_service_home=0x7f03001f;
        public static final int mm_title_bar_1=0x7f030020;
        public static final int mm_title_bar_2=0x7f030021;
        public static final int mm_user_home=0x7f030022;
        public static final int mm_user_home_item=0x7f030023;
        public static final int mm_user_home_userinfo=0x7f030024;
        public static final int mm_user_home_vip=0x7f030025;
        public static final int mm_user_name_view=0x7f030026;
        public static final int mm_wait_pay=0x7f030027;
        public static final int mm_wait_progress=0x7f030028;
        public static final int mm_web_2=0x7f030029;
        public static final int mm_widget_float_view=0x7f03002a;
        public static final int mm_xlistview_footer=0x7f03002b;
        public static final int mm_xlistview_header=0x7f03002c;
        public static final int select_head_menu=0x7f03002d;
        public static final int snake_notification=0x7f03002e;
        public static final int union_aaa_dialog=0x7f03002f;
    }
    public static final class string {
        public static final int Weixin_app_id=0x7f070006;
        public static final int app_name=0x7f070000;
        public static final int mm_xlistview_footer_hint_normal=0x7f07000b;
        public static final int mm_xlistview_footer_hint_ready=0x7f07000c;
        public static final int mm_xlistview_header_hint_loading=0x7f070009;
        public static final int mm_xlistview_header_hint_normal=0x7f070007;
        public static final int mm_xlistview_header_hint_ready=0x7f070008;
        public static final int mm_xlistview_header_last_time=0x7f07000a;
        public static final int snake_checknet=0x7f070005;
        public static final int snake_downloaderror=0x7f070004;
        public static final int snake_pleasewait=0x7f070003;
        public static final int snake_updateto=0x7f070002;
        /**  下载apk 
         */
        public static final int snake_updating=0x7f070001;
    }
    public static final class style {
        /**  <item name="android:windowAnimationStyle">@android:style/Animation.Translucent</item> 
 <item name="windowEnterAnimation">@anim/translucent_enter</item> 
 <item name="windowExitAnimation">@anim/translucent_exit</item> 
         */
        public static final int Animation=0x7f080003;
        public static final int MMDialogStyle=0x7f080001;
        public static final int UnityThemeSelector=0x7f080000;
        public static final int loading_dialog=0x7f080004;
        public static final int mm_button_type=0x7f080006;
        /** 中尺寸的按钮
         */
        public static final int mm_button_type_2=0x7f080007;
        public static final int mm_input_box_type=0x7f080005;
        public static final int mm_input_box_type_2=0x7f080008;
        public static final int sdkTransparent=0x7f080002;
    }
    public static final class xml {
        public static final int file_paths=0x7f040000;
    }
}
